lvgl_nuttx:add missing header file
unistd.h for gettid

apps/graphics/lvgl/lvgl/src/drivers/nuttx/lv_nuttx_image_cache.c:146:89: warning: implicit declaration of function 'gettid' [-Wimplicit-function-declaration]
  146 |     lv_snprintf(ctx->name, sizeof(ctx->name), HEAP_NAME "[%-4" LV_PRIu32 "]", (uint32_t)gettid());

Signed-off-by: anjiahao <anjiahao@xiaomi.com>