fix(sysmon): skip unused function when profiler is not enabled
lv_sysmon_perf.c:418:17: error: 'lv_sysmon_perf_gen_tid' defined but not used [-Werror=unused-function]

Signed-off-by: Zhe Weng <wengzhe@xiaomi.com>